/*
date: April 17, 2020
author: Asumi
purpose: 
*/
import java.util.Scanner;
import java.util.Random;
class NumberGuessingGame {
    final int MAXNUM = 999;
    int secretNumber;  // secret number generated by the computer

    //constructor to initialize secret by generating a random integer in range 0 ~ MAXNUM
    NumberGuessingGame() {   
        Random rand = new Random(); 
        secretNumber = rand.nextInt(1000);      
    }

    void playGame() {
        Scanner in = new Scanner(System.in);
        int guess = 0;
        int count = 0;
        boolean win = false;
            System.out.print("Guess secret number;");
            guess = in.nextInt();
            do{ 
                if(count> 0){
                    System.out.println("You have"+(10-count)+"times more.");
                System.out.print("Guess number;");
                guess = in.nextInt();
                }  
                if(guess < secretNumber){
                    System.out.println("Too small;");
                    count++;
                }
                else if(guess > secretNumber) {
                    System.out.println("Too large;");
                    count++;
                }else{
                    win = true;
                }                            
            }while (win!= true && count<10);   
                if(guess == secretNumber){
                    win = true;
                        System.out.println("Congratulations, you won the game! You got it in"+count+"tries");
            }else
                System.out.println("“Sorry, you lost the game! The answer should be"+secretNumber);
            }
}
                               
public class NumberGuessGame {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        NumberGuessingGame myGame = new NumberGuessingGame();
        String res;
        do {
            myGame.playGame();
            
            System.out.print("Play again(y or n): ");
            res = in.next();
        } while (res.toLowerCase().charAt(0) == 'y');
        System.out.println("Thanks for playing, bye!");
    } 
}